### ISSUE TITLE
unable to compile on CentOS 6.3

### ISSUE THREAD

**Issue by arm2arm** [bieh/clustergl#8]
How to reproduce:
git clone https://github.com/bieh/clustergl.git
cd clustergl/

clustergl]$ make 
make -C src
make[1]: Entering directory `/home/arm2arm/Projects/clustergl/src'
g++  -I/opt/local/include/ -Iinclude -O3 -Wextra -g -fPIC -fvisibility-inlines-hidden    -c -o config.o config.cpp
In file included from include/main.h:16,
                 from config.cpp:4:
include/libs.h:46:21: error: confuse.h: No such file or directory
include/libs.h:74:25: error: SDL/SDL_net.h: No such file or directory
config.cpp: In constructor 'Config::Config(std::string, std::string)':
config.cpp:14: error: 'cfg_opt_t' does not name a type
config.cpp:31: error: 'cfg_opt_t' does not name a type
config.cpp:49: error: 'cfg_t' was not declared in this scope
config.cpp:49: error: 'cfg' was not declared in this scope
config.cpp:51: error: 'opts' was not declared in this scope
config.cpp:51: error: 'CFGF_NONE' was not declared in this scope
config.cpp:51: error: 'cfg_init' was not declared in this scope
config.cpp:53: error: 'cfg_parse' was not declared in this scope
config.cpp:55: error: 'CFG_FILE_ERROR' was not declared in this scope
config.cpp:60: error: 'CFG_PARSE_ERROR' was not declared in this scope
config.cpp:65: error: 'cfg_getstr' was not declared in this scope
config.cpp:72: error: 'cfg_getstr' was not declared in this scope
config.cpp:80: error: 'cfg_size' was not declared in this scope
config.cpp:90: error: 'o' was not declared in this scope
config.cpp:90: error: 'cfg_getnsec' was not declared in this scope
config.cpp:94: error: 'cfg_getstr' was not declared in this scope
config.cpp:95: error: 'cfg_getint' was not declared in this scope
config.cpp:100: error: 'cfg_title' was not declared in this scope
config.cpp:113: error: 'cfg_getfloat' was not declared in this scope
config.cpp:135: error: 'cfg_free' was not declared in this scope
make[1]: **\* [config.o] Error 1

**Comment by arm2arm** [comment]
ok Fixed:
sudo yum install libconfuse-devel
sudo yum install SDL_net-devel
